settings:
  display: 'Foursquare'
  page_url: 'https://foursquare.com'
  base_url: 'https://foursquare.com/explore?mode=url'
  parameters:
    - key: q
      property: name
    - key: near
      property: long_address
  mapping:
    name:
      css: '#resultsView .recommendationList .card:first .venueName h2 a'
    address:
      css: '#resultsView .recommendationList .card:first .venueAddress'
    url:
      xpath: '//*[@id="results"]/ul/li[1]/div[2]/div[1]/div[1]/div/div[1]/h2/a/@href'
