settings:
  display: 'MapQuest'
  page_url: 'http://www.mapquest.com'
  base_url: 'http://www.mapquest.com/search/results'
  html_fields:
    - full_address
  parameters:
    - key: query
      property:
        - name
        - small_address
  mapping:
    name:
      css: 'ol.search-results li:first span h3 a'
    full_address:
      css: 'ol.search-results li:first span span'
    url:
      xpath: '//ol[@class="search-results"]/li[1]/span/h3/a/@href'
