settings:
  page_url: 'http://www.switchboard.com'
  base_url: 'http://www.switchboard.com/business'
  parameters:
    - key: key
      property: name
    - key: where
      property: small_address
  mapping:
    name:
      css: '.map-entries > li:first .primary-content p.name'
    full_address:
      css: '.map-entries > li:first .secondary-content .first div span'
      options: list
    url:
      xpath: '//*[@class="map-entries"]//li[0]//a[@class="link-wrapper clickstream-link"]/@href'
