settings:
  display: 'Yelp'
  page_url: 'http://www.yelp.com'
  html_fields:
    - full_address
  base_url: 'http://www.yelp.com/search'
  parameters:
    - key: find_desc
      property: name
    - key: find_loc
      property: small_address
  mapping:
    name:
      css: '#super-container > div > div.clearfix.layout-block.layout-a.scroll-map-container.search-results-block > div.column.column-alpha > div > div.search-results-content > ul:nth-child(2) > li.regular-search-result > div > div > div.main-attributes > div > div.media-story > h3 > span > a > span'
    full_address:
      css: '#super-container > div > div.clearfix.layout-block.layout-a.scroll-map-container.search-results-block > div.column.column-alpha > div > div.search-results-content > ul:nth-child(2) > li.regular-search-result > div > div > div.secondary-attributes > address'
      options: html
    phone_number:
      css: '#super-container > div > div.clearfix.layout-block.layout-a.scroll-map-container.search-results-block > div.column.column-alpha > div > div.search-results-content > ul:nth-child(2) > li.regular-search-result > div > div > div.secondary-attributes > span.biz-phone'
    url:
      xpath: '//*[@class="search-results-content"]//*[@class="regular-search-result"]//a[@class="biz-name"]/@href'
