# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acb75d7837de46058c0c286b2e87e329d793101943c7c2125e3ee9042331b09dd4eea6b01d838c91f399879ed0f44fb6647593c95d5bf305efae0e71666a6450

test:
  secret_key_base: df7b7ea43b75ee0bea20dc161bdb7ae90f26c3cd81b439f83485db31b465197a5cb535c5e3953d79a45d7053e8fd8e2f8715efb19bba0ac2edf1560e64e0957b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
